### ISSUE TITLE
avoid html injection some more

### ISSUE THREAD

**Issue by greggles** [mattiasgeniar/drupal-enginehack-detector#1]
http://enginehack.ma.ttias.be/queue.php?url=http://example.ee/sdsf%22f%3E%3Cplaintext%3E ;)

**Comment by greggles** [comment]
You are doing some avoiding of this already which seemed to block the xss attempts I tried.

Here's a more jolly version http://enginehack.ma.ttias.be/queue.php?url=http://example.ee/sdsf%22f%3E%3Cmarquee%3E

**Comment by greggles** [comment]
Hattip to @c4rl on the marquee version.

**Comment by mattiasgeniar** [comment]
Thanks for reporting, that should be patched in the latest commit!
